package sql.handler;

import custom.TestHelper;
import org.junit.Test;
import org.zaizai.sachima.constant.TokenFnvConstants;
import org.zaizai.sachima.sql.dialect.mysql.visitor.handler.ColumnTypeHandler;
import org.zaizai.sachima.sql.dialect.mysql.visitor.handler.PrimaryKeyHandler;

import java.util.Objects;

/**
 * <H1></H1>
 *
 * @author Qingyu.Meng
 * @version 1.0
 * @date 2023/3/23 11:23
 */
public class PrimaryKeyHandlerTest extends TestHelper {

    @Test
    public void case0 () {
        assert PrimaryKeyHandler.getTablePrimaryKey("sachima") == null;
        String var0 = "CREATE TABLE \"C##EARCHIVES\".sachima\n" +
                "(\n" +
                "    id              NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    name            VARCHAR2(20),\n" +
                "    CONSTRAINT PK_EA_EXPENSE_VOUCHER_ROW PRIMARY KEY (id)\n" +
                ")";
        PrimaryKeyHandler.refresh(getStatement(var0));
        assert Objects.equals(PrimaryKeyHandler.getTablePrimaryKey("sachima"), "ID");
    }

}
