package sql.handler;

import custom.TestHelper;
import org.junit.Test;

import java.util.Objects;

/**
 * <H1></H1>
 *
 * @author Qingyu.Meng
 * @version 1.0
 * @date 2023/3/23 11:23
 */
public class PrimaryKeyHandlerTest extends TestHelper {

    @Test
    public void case0 () {

        assert handler.getTablePrimaryKey("primary_key_table") == null;
        String var0 = "CREATE TABLE \"SACHIMA\".primary_key_table\n" +
                "(\n" +
                "    id              NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    name            VARCHAR2(20),\n" +
                "    CONSTRAINT PK_EA_EXPENSE_VOUCHER_ROW PRIMARY KEY (id)\n" +
                ")";
        handler.onEvent(getStatement(var0));
        assert Objects.equals(handler.getTablePrimaryKey("primary_key_table"), "ID");
    }

}
