package sql.ddl;

import custom.TestHelper;
import org.junit.Test;
import org.zaizai.sachima.sql.ast.SQLStatement;

/**
 * <H1></H1>
 *
 * @author Qingyu.Meng
 * @version 1.0
 * @date 2023/1/10 14:19
 */
public class CreateTableTest extends TestHelper {


    @Test
    public void case1() {
        //String sql = "CREATE TABLE EARCHIVESTEST.ea_form\n" +
        //        "(\n" +
        //        "    id                 NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY  NOT NULL,\n" +
        //        "    name               VARCHAR2(100)                                  NOT NULL,\n" +
        //        "    type               VARCHAR2(60)                                   NOT NULL,\n" +
        //        "    modify               VARCHAR2(50)                                   NOT NULL,\n" +
        //        "    is_enabled         NUMBER(1) DEFAULT 1                            NOT NULL,\n" +
        //        "    is_deleted         NUMBER(1) DEFAULT 0                            NOT NULL,\n" +
        //        "    tenant_id          NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    parent_id          NUMBER(38, 0),\n" +
        //        "    form_group_id      NUMBER(38, 0),\n" +
        //        "    created_by         NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    created_date       TIMESTAMP DEFAULT sysdate                      NOT NULL,\n" +
        //        "    last_modified_by   NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    last_modified_date TIMESTAMP DEFAULT sysdate                      NOT NULL,\n" +
        //        "    CONSTRAINT PK_EA_FORM PRIMARY KEY (id)\n" +
        //        ");\n";
        //SQLStatement statement = getStatement(sql);
        //System.out.println(statement);
    }

    @Test
    public void case2() {
        //String sql = "CREATE TABLE EARCHIVESTEST.ea_form_field\n" +
        //        "(\n" +
        //        "    id                 NUMBER(38, 0) NOT NULL,\n" +
        //        "    name               VARCHAR2(100)                                  NOT NULL,\n" +
        //        "    code               VARCHAR2(60)                                   NOT NULL,\n" +
        //        "    form_id            NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    widget_type        VARCHAR2(60)                                   NOT NULL,\n" +
        //        "    input_manually     NUMBER(1) DEFAULT 1                            NOT NULL,\n" +
        //        "    required           NUMBER(1) DEFAULT 1                            NOT NULL,\n" +
        //        "    remark             VARCHAR2(255),\n" +
        //        "    is_deleted         NUMBER(1) DEFAULT 0                            NOT NULL,\n" +
        //        "    is_enabled         NUMBER(1) DEFAULT 1                            NOT NULL,\n" +
        //        "    tenant_id          NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    created_by         NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    created_date       TIMESTAMP DEFAULT sysdate                      NOT NULL,\n" +
        //        "    last_modified_by   NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    last_modified_date TIMESTAMP DEFAULT sysdate                      NOT NULL,\n" +
        //        "    sort_number        INTEGER                                        NOT NULL,\n" +
        //        "    modify             NUMBER(1) DEFAULT 1                            NOT NULL,\n" +
        //        "    CONSTRAINT PK_EA_FORM_FIELD PRIMARY KEY (id)\n" +
        //        ")";
        //System.out.println(mysqlToOracle(sql));
    }

    @Test
    public void case3() {
        String sql = "comment on COLUMN EARCHIVESTEST.ea_form_field.modify is '是否支持修改';";
        SQLStatement statement = getStatement(sql);
        System.out.println(statement);
        System.out.println(mysqlToOracle(sql));
    }

    @Test
    public void case4() {
        //String sql = "CREATE TABLE EARCHIVESTEST.ea_document_recycle\n" +
        //        "(\n" +
        //        "    id          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
        //        "    tenant_id   NUMBER(38, 0),\n" +
        //        "    document_id NUMBER(38, 0)                                  NOT NULL,\n" +
        //        "    delete_time TIMESTAMP DEFAULT sysdate                      NOT NULL,\n" +
        //        "    CONSTRAINT PK_EA_DOCUMENT_RECYCLE PRIMARY KEY (id),\n" +
        //        "    CONSTRAINT uk_document_id UNIQUE (document_id)\n" +
        //        ")\n";
        //System.out.println(mysqlToOracle(sql));
    }
}
